import { camelCase } from '../lib'

describe('camelCase', () => {
  it('convert string to camel case', () => {
    expect(camelCase('foo')).toBe('foo')
    expect(camelCase('foo-bar')).toBe('fooBar')
    expect(camelCase('foo-bar-baz')).toBe('fooBarBaz')
    expect(camelCase('foo--bar')).toBe('fooBar')
    expect(camelCase('--foo-bar')).toBe('fooBar')
    expect(camelCase('--foo--bar')).toBe('fooBar')
    expect(camelCase('FOO-BAR')).toBe('fooBar')
    expect(camelCase('FOÈ-BAR')).toBe('foèBar')
    expect(camelCase('-foo-bar-')).toBe('fooBar')
    expect(camelCase('--foo--bar--')).toBe('fooBar')
    expect(camelCase('foo.bar')).toBe('fooBar')
    expect(camelCase('foo..bar')).toBe('fooBar')
    expect(camelCase('..foo..bar..')).toBe('fooBar')
    expect(camelCase('foo_bar')).toBe('fooBar')
    expect(camelCase('__foo__bar__')).toBe('fooBar')
    expect(camelCase('__foo__bar__')).toBe('fooBar')
    expect(camelCase('foo bar')).toBe('fooBar')
    expect(camelCase('  foo  bar  ')).toBe('fooBar')
    expect(camelCase('-')).toBe('-')
    expect(camelCase(' - ')).toBe('-')
    expect(camelCase('fooBar')).toBe('fooBar')
    expect(camelCase('fooBar-baz')).toBe('fooBarBaz')
    expect(camelCase('foìBar-baz')).toBe('foìBarBaz')
    expect(camelCase('fooBarBaz-bazzy')).toBe('fooBarBazBazzy')
    expect(camelCase('FBBazzy')).toBe('fbBazzy')
    expect(camelCase('F')).toBe('f')
    expect(camelCase('FooBar')).toBe('fooBar')
    expect(camelCase('Foo')).toBe('foo')
    expect(camelCase('FOO')).toBe('foo')
    expect(camelCase('foo', 'bar')).toBe('fooBar')
    expect(camelCase('foo', '-bar')).toBe('fooBar')
    expect(camelCase('foo', '-bar', 'baz')).toBe('fooBarBaz')
    expect(camelCase('', '')).toBe('')
    expect(camelCase('--')).toBe('')
    expect(camelCase('')).toBe('')
    expect(camelCase('--__--_--_')).toBe('')
    expect(camelCase('---_', '--', '', '-_- ')).toBe('')
    expect(camelCase('foo bar?')).toBe('fooBar?')
    expect(camelCase('foo bar!')).toBe('fooBar!')
    expect(camelCase('foo bar$')).toBe('fooBar$')
    expect(camelCase('foo-bar#')).toBe('fooBar#')
    expect(camelCase('XMLHttpRequest')).toBe('xmlHttpRequest')
    expect(camelCase('AjaxXMLHttpRequest')).toBe('ajaxXmlHttpRequest')
    expect(camelCase('Ajax-XMLHttpRequest')).toBe('ajaxXmlHttpRequest')
  })
})
